name:                scheme
version:             0.1
synopsis:            Write You a Scheme

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

dependencies:
- base  >= 4.8 && <5.0
- classy-prelude
- bytestring
- containers
- directory
- haskeline
- mtl
- optparse-applicative
- megaparsec
- text
- transformers
- HTTP
- tasty
- tasty-golden
- hspec

ghc-options:
- -Weverything

executables:
  scheme:
    main: Main.hs
    source-dirs: exec
    dependencies:
    - base >= 4.8 && < 5
