name:                scheme
version:             0.1
synopsis:            Write You a Scheme

default-extensions:
- OverloadedStrings

dependencies:
- base  >= 4.8 && <5.0
- bytestring
- containers
- directory
- haskeline
- mtl
- optparse-applicative
- megaparsec
- text
- transformers
- HTTP
- tasty
- tasty-golden
- hspec

ghc-options:
- -Weverything

library:
  source-dirs: src/

executables:
  scheme:
    main: Main.hs
    source-dirs: exec
    dependencies:
    - base >= 4.8 && < 5
    - scheme
  docs:
    main: Build.hs
    dependencies:
    - base >= 4.8 && < 5.0
    - shake
    - pandoc

tests:
  test:
    main: Main.hs
    source-dirs: test-hs/Spec/
    dependencies:
    - scheme
    - hspec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  test-golden:
    main: Main.hs
    source-dirs: test-hs/Golden
    dependencies:
    - scheme
    - tasty
    - tasty-golden
    - bytestring
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
